name: Publish the website
on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0 # fetch all commits and branches for mike to work properly
      - uses: actions/setup-java@v3
        name: Set up Java 17
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: 3.x
      - name: Tools setup
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" --output smallrye-sign.asc .github/release/smallrye-sign.asc.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" --output maven-settings.xml .github/release/maven-settings.xml.gpg
          gpg --fast-import --no-tty --batch --yes smallrye-sign.asc
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"
          cd docs
          sudo snap install yq
          pip3 install pipenv
          pipenv install
          cd ..
      - name: Build local artifacts
        run: mvn -B install -DskipTests -Prelease -s maven-settings.xml
      - name: Render docs and publish
        run: .github/render-documentation.sh